apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bepi1x3eLCB2+kd0NVMqtoCOjgT9gFLI1JObVe75cUNkl1SA8ZMvVY7+24HP0w==,iv:g2QCzc9XqtGLbZVejWe6VSsMvJH1g1CXl8x+nBVpP9M=,tag:olnQWmnF/zS2xtbGjKFn+Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:qsgBs9TLHRNaKHwef5lBS5S/LPMOD2Ek6az1HKdF/R3kQMxE3Q==,iv:R7FU7cE5GCLecgsik0XN4SHRNgq4gbLIwerylSwMEZk=,tag:O6+HUFkBnQUS36fWaYrT2A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:U/lfSwrHdBeN0n9hWG0g2EfYLjGbmVW3/to=,iv:dKe8t/Tuxs5XTZg9tenl+FYeboA50Z+JcA5lXZHdapo=,tag:ufsL7/yt+CCuhSfa7wKERg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbW1XdzRwTzVqY3RDejd2
            UEdSenA1MGRRRHZxZ3pyVFZyVzF1RzZTcEhjCktTMmdzMzhyMVVBeC9aSERYejNp
            cXh6eWd6aFJyanBxaDJ1d21lQ0JvcWMKLS0tIFpFdTNhendValo2bHZ0V3E1V1FN
            V1dyc0lLYi9nQXIzdnd3OEpRWTJLZHMKrrtTlkX4xTbcqbaYKuBHjWS4+/cDriGu
            N9aDhC/G8cAan595mUOh6LYhYNA4VSff3+Wsb7RVnnsjI3MKn/5oVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T16:40:11Z"
    mac: ENC[AES256_GCM,data:3wuwNGeXLxFPlVw5gzDns+J6z87x7w7yC6pybdgpBaIajw5gGqS07Bo06rZhdE/866ewKh/KscOyJv+Aboeu6DwcDzIKYRkPWYEUp7/dm5VDzO/Kj4aW9pz2KmXCm8H+4QA7y/XlMokL8igw8YXvzSYHuX0Y5e7+LePeFUejayw=,iv:uRKxatMZcqHHZcModZuXZqq2RqjBWldyp9ak9ovY55k=,tag:k5MyTPIFXhQOcNS8AOgzsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
