---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
