---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
