kind: ENC[AES256_GCM,data:NSjkYHj2,iv:C0s6v+dY1BAt3nPUMA8rJ9XwVVX9c9r7USPifC1lf6E=,tag:p+pmubZC6l/Aj81xCVjCmw==,type:str]
ansible_user: ENC[AES256_GCM,data:1aLScIM=,iv:RjGT7eKa01RFTSOOrG6ffjystv0ySmK3yJw+jw4nUqU=,tag:Gb+ZsUC6jMl+v+aJCTNFCg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:muJceHooOJDvVZov,iv:s/AKRefozx5EwYtedXCCToNowgEH20n19iYagt24phk=,tag:B1ZJ0mh4jeIdrTIgyCNypA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWldKK0J2cWsvbWN3djhS
            bkxycmxqbGFxNXpBUTZmRGEzY3UvYU4wZzBrCnM1TFUwcklGM3ZkSk9pZFFpdUF5
            VzJRWk5IWTA2WUpFb2k1ZkVMSzgyRXcKLS0tIEsrcEhTaEJtSjgvak1ENGpsVjU2
            ZHl6TXlvTHN3dWtVTXpBMnVuT21NalkKwxzn92Ovuf7pRImpoSmiqWfe+tO1NDOr
            /WNUZApLeXo4C3kwUoFM8BJKbAxmmHese/P36HunpKqgdW63z5BjYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T23:56:48Z"
    mac: ENC[AES256_GCM,data:8L5HevY2SyDXH48DrGtEI+fk+Bp90t8vAsXpwKDFp9kjUxYPVZDFDiJ7F90rpE786O/Ap1U8YYGqwumCbYwNG0rtQfbUQa2VAuHbhq1XD4aWwSGzOZLBQ7+ACoHw1dUGtp2HXJS9BdvKljjJsTOBo/+Zw5+cWFdBC2sL5MPHdRc=,iv:cCyt5I6V8T85kTSigewFnF1SWlWNIi2LbqWyKv2bcLc=,tag:RZMfYl7t3iTRPolhZMvcDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
