kind: ENC[AES256_GCM,data:drnVr5U+,iv:MJeaWG2uJ0P6Tyqg7epHzBk41gWETICoG9fgYw5yI08=,tag:ShvGvEnaoYrGDQCXnZ9Yig==,type:str]
ansible_user: ENC[AES256_GCM,data:2lSDVxc=,iv:lDhqjmMr9kIDrQI+aCy3cCKj1PU51RMtrFGcQ//Brw8=,tag:iAEduP3MnBiph59DwVPJ5A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:TBghPDG6abLF63iH,iv:WHcfF8tljUU/xpqI+cMyb/EefDTVBPD7b2TP+Llqim0=,tag:NZCofkA6WMDIvqNvr/J+Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TXNTTU5zQTNjUmVrVDdz
            S3FVUktzdzdVWFRIelFtWGtLY1V4WnJrMkZBClo4M1JUZkxaOEdJdzFCTEh5Uk5q
            Y0JWK0JmWkhxVTdTWVVud2E3NElZVFkKLS0tIEl3Y09vbUlMaEJFb3VKcXFDYlRx
            bjB2WWhMbnQvM0ZjQkRJWWh0czFMQWcKr+DE0NKGoytGrLYrgfqfqaCZ4mJrd/yM
            4Lnpd0N9+IGmnVWXEcLqaOcg5Sow2ncqpbXSwWKSHlXznb0fu9+IsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T23:56:48Z"
    mac: ENC[AES256_GCM,data:ebQaEb3x07kF+7pEth8AkofMoxJJVnpJqkzLL/Uj6y8ZXaOODG9ZPw0E852l/pXeTZj6x2U+wM5vSHpzmgcwZnf0wVVlfusQJ2fCpuxOAYMSSxEPzBz7kimZCMuWp1rwYLX7Cp2Bxsk6jzbYyglcZyRF8/oL8Hr7reQ6zh3he/U=,iv:62KdSxOVff73alIcwwUnul3DZhMEEYGnwiU6nyrw5RM=,tag:XLfyCeBxuuPiaHkF8i/+tQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
