apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EWZUlJpvqzZZPLotfkhkjjzx0Hge63frWk2AsiyGUG9zcFyWHDBNpA==,iv:LYyRXT/q099kRGGDl2GizKnuzcFUmLQtHFgS3y/TZiI=,tag:ErYUqBnmB1SRKufj+/32Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tfxnwk3gwshkg8mdq5jwy8tzm385c7grkmtlf83pantxaarwspnq2sd5r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Zkp2L0dsVjVtZmwzbjZS
            eTRxTksxNjVFTEdoZ1dtbEZVR0pvdUN1dEdNCk5FTk1vQ0VnTHJ0ZXR2R0EydElG
            UnRsNWN5SnNxZ2JTaWl2b0ZGYWF3MTQKLS0tIEtUM2pXYlRqdTJXQXU2cTZ3ZUxt
            WTZYVzhNSGFrdWFWelN2Q2RrRmtPRGsKv2+UChekG7eBZ64qQJxk8yC6ukOQulvF
            K97bSrGbcnOD7uLTYTs2Ot63wQKRe38PaXf0gT2+c+P4ebez2K2djQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T16:14:17Z"
    mac: ENC[AES256_GCM,data:Yd1LTGbkMQnTW8GQyR+SFeV9KwLwnIC0mSWuNQTyCN/HkdHz7KvCR/8LTajO6w81sSxvLYB7LjU4bu6qtFknes2P2NgUEHJUXlKak9Ar0YAepLSYFFnFRuG167e24cKpGg7EiUKtx3qBaaDC6sag0YuhyiNp8xo+HShtscTikN8=,iv:qDV8rwatx3uRpKbhcCf/YaU+AL2DJuorLDGf7sJeIU8=,tag:6XnfWTGDSc9dWI7IO+IpvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
