---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.90.39
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.0.90.65
        k8s-2:
          ansible_host: 10.0.90.84
