apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:e7GESDH1wSDznSf8A+ZofyVgU2mWFe6sL4hLv5MLMmgkuQcM/VdqoNCXwbG0eMUcio5b6Knab1wskzp1,iv:1ouPBw5QAFYVyf1IzHD6OO0pJrrbkfTYWmxvaIDE19k=,tag:Qw2YtE+KfzglsTn9BD69WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjNFRDFtWERXN05qamhC
            MnRyVU1OankreWx0Tm1kZ1NVaWxjL1Q5c2tNCmEwTEs2MHFQQVFiN0RkNWp4SWFU
            Zzl1c2dLd28xMy9qczIxOWs1Y2lOQ00KLS0tIDZiNlBrSjVFRURUbnFpc3loNlN1
            TSs0Rk9PbVBMeDVLNHEyUHZHN0duNlEKMQpsbeQ6EguMqqYjc99++7HiQVpi3Z/T
            5a9epyPB8Figfl7LeczmvHEB4kKLAnM0l/hBbsAsycmNJJa+New6kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T16:40:11Z"
    mac: ENC[AES256_GCM,data:HP71jwGDxMQxnnkPfRnAO+y+DlLjSlDzL0jJVpyiB1n9DniATrpZpUf4oThD5i6Gc56mjpEsDcg5+SS8+kKPsnGe0cI4ker2c0odwIp1tmE5nGuy7bJqdQ41ebtNs+U0hsU6QiX1FLiqRi7KK/LCiTmuQUkEBnko9tXVVwSRpVs=,iv:LH76XwtCYRMPv+dhjeV/GRF6oFZ59yO40ce8dRhz8ek=,tag:G7KHW3me6ofBvV48sC4ZWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
