apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:E+OKU06TuF1L0TLU5KqtPeqiTEW9aLT3KtEuFmzn0f2FJYPx,iv:kaKXB8zMcZZMEbCRHiQgeMq24Vwh9rlGPhKYMVkL/AU=,tag:gdl0g2cGRjPI5oMJb//tbg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Zi0YUsFBKIJCgV8DMu3bB9YgSE27qX50Ovg/fsFk9c5/ZP1HapzBlkOLyZ+WTA==,iv:mAS2V9gn15k9K0FFIGdvTjBz6M0iPkYwNlxzNhjKI7A=,tag:ziS44dJqrIY2avW7yhTquQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujy2qdfqxlfxd54unj0qcfu74rxg7n7auu5c0tqu6gvsg7qpgg6sqjrxpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZmdxYUliYWMvSzZZMDkv
            b0dJTzMwejE0d0xzTmlKUlBSeHZQUk1UQmlJClg4UnRnSFpLazVlQkh2d0JhWUpj
            VmJqVE1uTW42NGUyNzJoWHlWV0tTcHcKLS0tIE0vd29OUk1jdDJlcUUvK05JYUxL
            MjlORVdVY1hvNDhEK0xEV1BpTnlRUjgK/tbtthWpp5UgUsmy0g4jeAHiSSU4nu3W
            zrhbHN4xwfhmheI5R7XWufCbXd7IZGbrXQxKBsxShH7GRKF9UA59NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T23:56:47Z"
    mac: ENC[AES256_GCM,data:sZxVBbegJRhLxg45tqtsEUxQtWUTGM7iRz3ke8qDMhMImr/TAowMWF2wfofDmM0xUngxXNi/pMUrMKT6klGroYDNgb26WSGClhLDp9Rx2duE6W0loRAzKfc2j01KFQcNzUUOSQ9OqboOqxs7yxSDfB6gNMpi1tqywqbld5FLiiw=,iv:RdYvI+8B36y0ePF1f095MNvKjw7KZ4frR9Ve6bmOhYU=,tag:BdTDGm80CmLuBn6EhJ7MRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
