apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZuSJz+GxVSb9/DmsoPND4OLuckdX,iv:pn4wU4lvHcIiUzk/0KIq5LkLKkNHtY6oi7NNi2qs/vY=,tag:Xl2P5qcUnFbUnpKyqIVgHg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zpSzcb+Ojb4SKOwWRumFkoOqyRxsUXWpLcMEReNrjhO7ptbzQZes8s5w9SajaA==,iv:pmXe5FLR/kku6+5ul7SoV/mopUsxWAtdSxiniWhvZvo=,tag:y+WOv3OHziSafoWSu7bOBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df4yv64m6dxnhn964x7q5k4dc3s80lm7sdpklt9g2cq06cgpcqnscd2nad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZzJBRzFjMFlsd0ZRcDFo
            ZDNmM2M0NjF3cVBsZDREQkkzR09TV0RaWUhNCmQvOUpnbGQ3UVUwTjdUV2VxUlc0
            SlE3ekI4cys2MFZRTDFTQUNycTlFbzgKLS0tIHAyeXM0V2Z1b3hsTklmdGY4RTht
            Z0pELzRvRld6SEw0YVdMamhLNVgwZncKWgGLMuGiI+IDxL8rkthrLIPRZfNdQ7GY
            6EiZr+rEyHWsvy/IykKg53lERzFooiRCIt5wgEUmwY/MAENJvbUCcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T16:40:11Z"
    mac: ENC[AES256_GCM,data:6Fih/0+MTJrhbAepJkCIw+L2m7p+nh5bzKcoxBx3m1bNDdf0UW2e74BGPydxy0cZ0KfFRXk/0wJzwxKcNnePfjW5lJYaPij6NMdXz1gq1GOoexjyJA2ortTmqqt8WW6bxjt4HVj314IQcasq2Gs37Z845uhwF0vi/L716NvuBnI=,iv:R/nGfT98Lwy6wnp/bwkObeHf9Gdj4u4kx6Vj0qU/f8I=,tag:Fwwihxcf50xBf4zvtgHU6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
