---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "10.0.90.100"
  METALLB_LB_RANGE: "10.0.90.101-10.0.90.111"
  METALLB_K8S_GATEWAY_ADDR: "10.0.90.101"
  METALLB_INGRESS_ADDR: "10.0.90.102"
