apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Vht3Q6x5Xg8kkDXnIpJPe4X7VgY8aUnfrBePIqeuI86LhZdL,iv:87jMqr0VIVH7bJ9M+2HYlA/X2b01cd+xV5WSN033bRE=,tag:A6KEf1ioko7tQC2Fpv36pg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5SWvHx9GN/iF6+4WvEGSyBPinDqCds0cRLXaSbBhHOrzrfD1PsHQk+/IGBI5Sw==,iv:HDjtHCJAIkFS9znXviW4oJPcLhIVSQ0fDS/OU7fBuM4=,tag:PC6vrEN3Y3HG0AxCyz/0jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tfxnwk3gwshkg8mdq5jwy8tzm385c7grkmtlf83pantxaarwspnq2sd5r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eldNWG53WDNYYnJLMEFL
            U3JGQ0xHZzVoVDBNMXVKTjkwbjR6dzZvU1RFCnJrRkFCcWhvSUJ3N015cnMzYmth
            N3Vob2JaOTdrdHlZWUlLNjJEZ0VIVlEKLS0tIGpJaWp3eHJwSTVabUNOQUdkcEU3
            aDc1NW44dkpYcVl4RFUvbnI5WCtGTlkKFkxUIY1ahJl3wLBVw7N/k7cVwxkne8la
            Kwsfol33vWs9z104daZGwQZyHvkIj5BxsxC9VAOf3QnRAUQJErWLNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T16:14:17Z"
    mac: ENC[AES256_GCM,data:tdzkRfNfbyn9XlSN/PYS3S/gm396uk+KXRq2k0kP779gZ5AeYDPlymh+Boe07nkXek853/TjZWDLXkabn6Rh+EoJhgA6bk2153ydKjOdiDoYOEFaqRFRrxqgqQqqNBiCNZRvFKcdKqlOeQg0lgaGlUWRX+po1kTNsJ0Qyee3DTA=,iv:7TSOWhD+UW8e6w5UztZIZamLLx28NNTmTXkM21/jS7g=,tag:3sk355lEDAxiYlnzEgpV+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
